### ISSUE TITLE
Legal action will be taken. - https://github.com/hisroyalty/clever-chat

### ISSUE THREAD

**Issue by hisRoyalty** [CodeWhiteWeb/Chatbot-discord#1]
Hello, as un-cruel as I want this to look, and I don't really want to waste my time here, clearly, that you have copied at least 90% of the code in this package for your own use and claiming it to be yours. Please take a look at the license and please give a link to this readme to the clever-chat repository, unless you want legal action to be taken.

On the other hand, your account is very shady, all projects are shady too. So please stop 'copying and claiming it' as it just ruins the github eco system.

Thanks,
HisRoyal

**Comment by CodeWhiteWeb** [comment]
You abandoned the Project, so I am just trying to make it keep going, I will add credit to your project, I just forgot to give the credits.
I use a https API which I created using dialogflow and I found you project which uses something similar which made it easier for me to do the work
